services: # Contains services
 nginx: # The nginx service is called (like a google dns to go to the site ip but here the internal dns has docker) and nginx is the server that serves wordpress
  build: requirements/nginx # Image path
  container_name: nginx # Name of container
  ports:
   - "443:443" # Binds port 80 of the container and host, to receive HTTPS requests
  depends_on:
   - wordpress
  restart: on-failure # Restart if crash
  volumes:
    - /home/rgobet/data/wordpress:/var/www/html
  networks:
   - inception
 wordpress:
  build: requirements/wordpress
  container_name: wp-php
  depends_on:
   - mariadb
  restart: on-failure
  env_file:
      - .env
  volumes:
   - /home/rgobet/data/wordpress:/var/www/html
  networks:
   - inception
 mariadb:
  build: requirements/mariadb
  container_name: mariadb
  restart: on-failure
  env_file:
      - .env
  volumes:
   - /home/rgobet/data/mariadb:/var/lib/mysql
  healthcheck:
   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MARIADB_ROOT_PASSWORD}"]
   interval: 10s
   timeout: 5s
   retries: 5
   start_period: 10s
  networks:
   - inception
networks:
 inception:
